### ISSUE TITLE
_run_with_pytest

### ISSUE THREAD

**Issue by alexmojaki** [friendly-traceback/friendly-traceback#175]
When I run tests in futurecoder, an obscure warning appears in the stderr captured by the tests. Not captured by pytest and shown in the terminal, but captured by the tests and affecting the results. The reason is this:

https://github.com/friendly-traceback/friendly-traceback/blob/dc32fc13ba2f9bc86b5b9bff625b21a5e2a3acf4/friendly_traceback/__init__.py#L53-L58

Please replace `_run_with_pytest` with something that is only turned on explicitly by your own tests, so that it doesn't affect other code using friendly-traceback and pytest at the same time. For example, you could set an environment variable. Alternatively, here's what I do in executing: https://github.com/alexmojaki/executing/blob/72a9ab419e46a7ea1a4ff950e4f5feeb98048e9a/tests/utils.py#L11

**Comment by aroberge** [comment]
Ok, I will try to implement something like this.

**Comment by aroberge** [comment]
New version uploaded to Pypi, which should not have this problem.

**Comment by alexmojaki** [comment]
`_run_with_pytest` within `about_warnings.py` still seems like it could theoretically be a problem, since other projects like futurecoder may see unintentionally different behaviour between tests and deployment. But now that I'm actually looking at `about_warnings` I'm becoming more worried about the fact that the general behaviour of `warnings` is patched globally in ways I don't understand at all. It's a theoretical concern, I haven't encountered anything in practice yet, but that still seems like something that should be optional.

**Comment by aroberge** [comment]
By default, warnings are ignored when importing friendly_traceback; this is what I assumed you'd want for futurecoder (and similarly for HackInScience). (At least, that's what I meant to do, and initially forgot about the effect of simply considering pytest.)

Since they are ignored, `warning.showwarning` has no effect.  When warnings are not ignored, with cPython there is a default version of `warning.showwarning` which gives the following:

```
# cPython
>>> import warnings
>>> warnings.simplefilter("always")
>>> [1, 2, 3]()
<stdin>:1: SyntaxWarning: 'list' object is not callable; perhaps you missed a comma?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'list' object is not callable
```
By default, when using friendly_traceback in interactive mode (i.e with its own console), I activate warning, and show something similar to what cPython does, but omitting the filename and linenumber:
```
> python -m friendly_traceback --python_prompt

Friendly-traceback version 0.7.5. [Python version: 3.9.10]
Type 'Friendly' for help on special functions/methods.

>>> [1, 2, 3]()
`SyntaxWarning`: 'list' object is not callable; perhaps you missed a comma?

Traceback (most recent call last):
  File "<friendly-console:1>", line 1, in <module>
    [1, 2, 3]()
TypeError: 'list' object is not callable
```
When running new tests, I want to see if some new warnings arise which I have not considered before. If they do, I plan to quickly add them so that "cause" will be known, and the warnings will never be displayed - which has the same visible effect for the end user as having the cPython default.

I also activate the warnings when using `friendly` (as opposed to simply using friendly_traceback).

So, the only problem would be if someone wants to process the warnings themselves, while using pytest and friendly_traceback at the same time since friendly_traceback's processing might take precedence depending on the order of imports.  If this creates a problem with another library, I will try to find a solution so that both can coexist. 

warnings processed by friendly_traceback will not interrupt a program, but they will still be available for inspection using `what()`, `where()`, `why()`, just like for tracebacks. However, this has to be done in an interactive settings, since warnings are otherwise just silently processed.

**Comment by alexmojaki** [comment]
> By default, warnings are ignored when importing friendly_traceback; this is what I assumed you'd want for futurecoder

I'm curious about the reasoning here. Do you find that warnings are generally more harmful than helpful for beginners? That certainly sounds plausible to me but it's not clear.

I'm also worried that users might try directly something like `warnings.warn` for the sake of learning/experimentation with the warnings module, and in that case I'd want the behaviour to be the same as the standard.

**Comment by aroberge** [comment]
Ok, I've hidden the global reassignment behind a function call. This should now be completely invisible to futurecoder and other libraries using friendly_traceback, unless they make the required function call.
